version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.11
    commands:
      - pip install --upgrade pip
      - pip install -r requirements.txt # Install project dependencies
      - pip install pylint # Install pylint for static code analysis
      - pip list # Print installed packages for verification

  pre_build:
    commands:
      - python --version # Print Python version for verification
      - pylint $CODEBUILD_SRC_DIR/manage.py || true # Run pylint on manage.py and ignore exit status
      - python $CODEBUILD_SRC_DIR/manage.py makemigrations # Run makemigrations command
      - python $CODEBUILD_SRC_DIR/manage.py migrate # Run migrate command

artifacts:
  files:
    - "**/*" # Include all files in the artifact
